Загружаем данные, смотрим их качество

In [6]:
import pandas as pd

df = pd.read_csv("superstore_dataset2011-2015.csv", encoding='latin-1')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,42433,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,Constantine,...,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408.300,2,0.0,106.140,35.46,Medium
1,22253,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.366,3,0.1,36.036,9.72,Medium
2,48883,HU-2011-1220,1/1/2011,5/1/2011,Second Class,AT-735,Annie Thurman,Consumer,Budapest,Budapest,...,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66.120,4,0.0,29.640,8.17,High
3,11731,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,Stockholm,...,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",44.865,3,0.5,-26.055,4.82,High
4,22255,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",113.670,5,0.1,37.770,4.70,Medium

In [7]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296804
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

Проводим EDA, добавляем новые колонки для удобства построения графиков

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True)
df['Ship Date']  = pd.to_datetime(df['Ship Date'],  format='mixed', dayfirst=True)

df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days

df = df[df['Shipping Duration'] >= 0]

df_clean = df[['Order ID', 'Order Date', 'Category', 'Sub-Category', 'City', 'Country', 
               'Sales', 'Profit', 'Shipping Duration', 'Quantity']]


df_clean['Year'] = df['Order Date'].dt.year
df_clean['Month'] = df['Order Date'].dt.month_name()


df_clean['Profit Margin'] = (df_clean['Profit'] / df_clean['Sales']) * 100

df_clean.to_csv('dashboard_ready.csv', index=False)

In [49]:
df_clean.head()

,Order ID,Order Date,Category,Sub-Category,City,Country,Sales,Profit,Shipping Duration,Quantity,Year,Month,Profit Margin
0,AG-2011-2040,2011-01-01,Office Supplies,Storage,Constantine,Algeria,408.300,106.140,151,2,2011,January,25.995591
1,IN-2011-47883,2011-01-01,Office Supplies,Supplies,Wagga Wagga,Australia,120.366,36.036,212,3,2011,January,29.938687
2,HU-2011-1220,2011-01-01,Office Supplies,Storage,Budapest,Hungary,66.120,29.640,120,4,2011,January,44.827586
3,IT-2011-3647632,2011-01-01,Office Supplies,Paper,Stockholm,Sweden,44.865,-26.055,120,3,2011,January,-58.074223
4,IN-2011-47883,2011-01-01,Furniture,Furnishings,Wagga Wagga,Australia,113.670,37.770,212,5,2011,January,33.227765